services:
  db:
    image: postgres:14
    container_name: weather_postgres
    environment:
      POSTGRES_DB: weather_data
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: P@$$w0rd!
    ports:
      - "5432:5432"
    volumes:
      - weather_db_data:/var/lib/postgresql/data
    networks:
      - weather_network

  weather_etl:
    build: .
    container_name: weather_etl
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - weather_network
    command: python src/etl_pipeline_api.py

volumes:
  weather_db_data:

networks:
  weather_network:
    driver: bridge
